export const mandirs = [
    { id: 1, mandirName: 'Allentown', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Atlanta', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Boston', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Bowling Green', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Byron', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Cherry Hill', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Chicago', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Cincinnati', tier: "Chapter", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Cleveland', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Colonia', tier: "Gold", link: '/kids-attendance', image: '' },
    { id: 1, mandirName: 'Dallas', tier: "Chapter", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Detriot', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Edmonton', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Houston', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Huntsville', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Jackson', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Lakeland', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Los Angeles', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Louisville', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Jacksonville', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'MDDC', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Nashville', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'New York', tier: "Chapter", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 2, mandirName: 'Parisppany', tier: "Platinum", link: '/india24', image: '/images/india24.jpg' },
    { id: 1, mandirName: 'Raleigh', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Regina', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'San Jose', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Toronto', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Tifton', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
    { id: 1, mandirName: 'Weehawken', tier: "Gold", link: '/kids-attendance', image: '/images/del.jpg' },
  ]